# **********************************************************
# Copyright (c) 2020-2025 Google, Inc.  All rights reserved.
# Copyright (c) 2023 Arm Limited        All rights reserved.
# **********************************************************

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of Google, Inc. nor the names of its contributors may be
#   used to endorse or promote products derived from this software without
#   specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL VMWARE, INC. OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.

# Github Actions workflow for aarch64 Continuous Integration testing.

name: ci-aarchxx
on:
  # Run on pushes to master and on pull request changes, including from a
  # forked repo with no "push" trigger, while avoiding duplicate triggers.
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

  workflow_dispatch:

jobs:
  aarch64-precommit:
    strategy:
      fail-fast: false
      matrix:
        # This job will run in parallel.
        include:
          - os: ah-ubuntu_20_04-c6g_4x-50
            sve: false
          - os: ah-ubuntu_20_04-c7g_4x-50
            sve: true
            sve_length: 256
          - os: ah-ubuntu_20_04-c7g_4x-50
            sve: true
            sve_length: 128
    runs-on: ${{ matrix.os }}
    name: aarch64-${{matrix.sve && 'sve-' || ''}}precommit${{matrix.sve_length && '-' || ''}}${{matrix.sve_length}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      # Cancel any prior runs for a PR (but do not cancel master branch runs).
      - name: Cancel previous runs
        uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'pull_request' }}

      # We also need origin/master for pre-commit source file checks in runsuite.cmake.
      # But fetching multiple branches isn't supported yet: actions/checkout#214
      # Pending PR that adds this support actions/checkout#155
      # TODO i#4549: When necessary support is available, remove/replace the
      # workaround here and from every job in other Github Actions CI workflows.
      - name: Fetch master
        run: git fetch --no-tags --depth=1 origin master

      - name: Create build directory
        run: mkdir build

      - name: Create build environment
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential \
            doxygen \
            git \
            libunwind-dev \
            libc6-dev \
            openssh-client \
            openssl \
            python3 \
            vera++ \
            zlib1g-dev

      - name: Set ptrace_scope to 0
        run: |
          echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope

      - name: Check current ptrace_scope
        run: |
          cat /proc/sys/kernel/yama/ptrace_scope
          if [[ `cat /proc/sys/kernel/yama/ptrace_scope` != "0" ]]; then echo "WARNING: ptrace_scope NOT SET TO 0"; fi

      - name: Setup cmake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: '3.26.4'

      - name: Run Suite
        working-directory: build
        run: ../suite/runsuite_wrapper.pl travis
        env:
          CI_BRANCH: ${{ github.ref }}
        if: ${{ matrix.sve == false || matrix.sve_length == '' }}

      - name: Run Suite with sve vector length ${{ matrix.sve_length }}
        working-directory: build
        run: ../tools/run_with_vector_length.py ${{ matrix.sve_length }} ../suite/runsuite_wrapper.pl travis
        env:
          CI_BRANCH: ${{ github.ref }}
        if: ${{ matrix.sve == true && matrix.sve_length != ''}}

      - name: Send failure mail to dynamorio-devs
        if: failure() && github.ref == 'refs/heads/master'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.DYNAMORIO_NOTIFICATION_EMAIL_USERNAME}}
          password: ${{secrets.DYNAMORIO_NOTIFICATION_EMAIL_PASSWORD}}
          subject: |
            [${{github.repository}}] ${{github.workflow}} FAILED
            on ${{github.event_name}} at ${{github.ref}}
          body: |
            Github Actions CI workflow run FAILED!
            Workflow: ${{github.workflow}}/x86-32
            Repository: ${{github.repository}}
            Branch ref: ${{github.ref}}
            SHA: ${{github.sha}}
            Triggering actor: ${{github.actor}}
            Triggering event: ${{github.event_name}}
            Run Id: ${{github.run_id}}
            See more details on github.com/DynamoRIO/dynamorio/actions/runs/${{github.run_id}}
          to: dynamorio-devs@googlegroups.com
          from: Github Action CI
